# Generated by Django 4.2 on 2023-04-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_todo_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='is_complete',
            new_name='complete',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='completion_at',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='updated_at',
        ),
    ]
